import type { LexiconWord } from '../../_types'

export const globalStorageLexicon: LexiconWord[] = [
  { word: 'breakpoints', kind: 'platform', scopes: ['global'], meaning: 'Drizzle migration journal breakpoint field.' },
  { word: 'bundle', kind: 'domain', scopes: ['global'], meaning: 'Runtime collection of generated artifacts loaded together.' },
  { word: 'contract', kind: 'domain', scopes: ['global'], meaning: 'Typed API agreement shared across boundaries.' },
  { word: 'database', kind: 'domain', scopes: ['global'], meaning: 'Persistent structured storage.' },
  { word: 'durable', kind: 'platform', scopes: ['global'], meaning: 'Cloudflare Durable Object persistence/runtime concept.' },
  { word: 'entries', kind: 'domain', scopes: ['global'], meaning: 'Many ordered manifest or journal records.' },
  { word: 'entry', kind: 'domain', scopes: ['global'], meaning: 'One ordered manifest or journal record.' },
  { word: 'journal', kind: 'domain', scopes: ['global'], meaning: 'Drizzle migration ordering metadata.' },
  { word: 'manifest', kind: 'domain', scopes: ['global'], meaning: 'Generated runtime list of migration artifacts.' },
  { word: 'memory', kind: 'domain', scopes: ['global'], meaning: 'Persisted user or agent recall.' },
  { word: 'migration', kind: 'domain', scopes: ['global'], meaning: 'Versioned database schema change.' },
  { word: 'migrations', kind: 'domain', scopes: ['global'], meaning: 'Many versioned database schema changes.' },
  { word: 'smoke', kind: 'domain', scopes: ['global'], meaning: 'Cheap deterministic readiness verification after a migration.' },
  { word: 'sql', kind: 'platform', scopes: ['global'], meaning: 'SQL migration artifact generated by Drizzle.' },
  { word: 'sqlite', kind: 'platform', scopes: ['global'], meaning: 'Private Durable Object SQLite storage layer under Drizzle.' },
  { word: 'storage', kind: 'domain', scopes: ['global'], meaning: 'Persistence substrate.' },
  { word: 'tag', kind: 'domain', scopes: ['global'], meaning: 'Drizzle migration journal tag.' },
  { word: 'text', kind: 'platform', scopes: ['global'], meaning: 'Text storage column or primitive text.' },
]
