// Generated by Brioela Brain Migration Manifest. Do not edit by hand.
import journal from '@/agents/brain/drizzle/meta/_journal.json'
import migration0000 from '@/agents/brain/drizzle/0000_handy_robbie_robertson.sql?raw'
import type { BrainMigrationBundle } from '@/agents/brain/_migrations/brain.migration.schema'

export const brainMigrationBundle: BrainMigrationBundle = {
	journal,
	migrations: {
		m0000: migration0000,
	},
}
