export const TRANSFER_PURPOSES = [
  "charity",
  "commercial_investment",
  "corporate_card",
  "credit_card",
  "dividend",
  "family",
  "financial_services",
  "good_sold",
  "goods_bought",
  "government",
  "insurance",
  "intergroup_transfer",
  "intra_group_dividends",
  "information_technology",
  "leasing",
  "loan_charges",
  "merchant_settlement",
  "mobile_wallet",
  "none",
  "non_resident_transfer_between_accounts",
  "pension",
  "personal_expenses",
  "prepaid_cards",
  "professional",
  "rental",
  "resident_transfer_between_accounts",
  "salaries",
  "telecommunications",
  "travel",
  "utility_bill",
] as const;

export type TransferPurpose = (typeof TRANSFER_PURPOSES)[number];
