import type { LexiconWord } from '../_types'

export const globalLexicon: LexiconWord[] = [
  { word: 'active', kind: 'predicate', scopes: ['global'], meaning: 'A state that is currently in force.' },
  { word: 'add', kind: 'action', scopes: ['global'], meaning: 'Put a new item into an existing collection.' },
  { word: 'agent', kind: 'role', scopes: ['global'], meaning: 'Stateful actor that owns AI behavior or durable runtime behavior.' },
  { word: 'all', kind: 'domain', scopes: ['global'], meaning: 'Complete collected set.' },
  { word: 'allowed', kind: 'predicate', scopes: ['global'], meaning: 'Permitted by a guard or policy.' },
  { word: 'absolute', kind: 'domain', scopes: ['global'], meaning: 'Canonical non-relative location.' },
  { word: 'append', kind: 'action', scopes: ['global'], meaning: 'Add an item to the end of an ordered log.' },
  { word: 'app', kind: 'domain', scopes: ['global'], meaning: 'Application instance or app-level runtime surface.' },
  { word: 'api', kind: 'platform', scopes: ['global'], meaning: 'Application programming interface boundary.' },
  { word: 'apply', kind: 'action', scopes: ['global'], meaning: 'Execute a prepared change.' },
  { word: 'argument', kind: 'platform', scopes: ['global'], meaning: 'Function call argument in source code.' },
  { word: 'at', kind: 'grammar', scopes: ['global'], meaning: 'Time relation word in timestamp identifiers.' },
  { word: 'async', kind: 'platform', scopes: ['global'], meaning: 'Asynchronous runtime behavior.' },
  { word: 'baseline', kind: 'domain', scopes: ['global'], meaning: 'Recorded existing guard debt that must not expand.' },
  { word: 'ban', kind: 'action', scopes: ['global'], meaning: 'Reject a forbidden code pattern.' },
  { word: 'backend', kind: 'domain', scopes: ['global'], meaning: 'Server-side Brioela runtime scope.' },
  { word: 'binding', kind: 'domain', scopes: ['global'], meaning: 'Named runtime dependency provided by a platform.' },
  { word: 'boundary', kind: 'domain', scopes: ['global'], meaning: 'Explicit crossing point between trust zones or layers.' },
  { word: 'body', kind: 'domain', scopes: ['global'], meaning: 'Request or message body content.' },
  { word: 'brain', kind: 'domain', scopes: ['global'], meaning: 'Brioela personal intelligence Durable Object domain.' },
  { word: 'bypass', kind: 'domain', scopes: ['global'], meaning: 'Code path that avoids an approved boundary.' },
  { word: 'brioela', kind: 'domain', scopes: ['global'], meaning: 'The product and codebase domain.' },
  { word: 'build', kind: 'action', scopes: ['global'], meaning: 'Construct a derived artifact.' },
  { word: 'bundle', kind: 'domain', scopes: ['global'], meaning: 'Runtime collection of generated artifacts loaded together.' },
  { word: 'call', kind: 'platform', scopes: ['global'], meaning: 'Function or method invocation in source code.' },
  { word: 'callable', kind: 'platform', scopes: ['global'], meaning: 'Agents SDK method exposed as typed RPC.' },
  { word: 'check', kind: 'action', scopes: ['global'], meaning: 'Validate a condition without mutating product state.' },
  { word: 'checked', kind: 'domain', scopes: ['global'], meaning: 'Time or value after a validation check ran.' },
  { word: 'clean', kind: 'predicate', scopes: ['global'], meaning: 'Having no guard violations.' },
  { word: 'clock', kind: 'domain', scopes: ['global'], meaning: 'Approved source of current time.' },
  { word: 'collect', kind: 'action', scopes: ['global'], meaning: 'Gather many items from a source.' },
  { word: 'created', kind: 'domain', scopes: ['global'], meaning: 'Creation time for an owned record.' },
  { word: 'config', kind: 'role', scopes: ['global'], meaning: 'Validated configuration boundary.' },
  { word: 'contract', kind: 'domain', scopes: ['global'], meaning: 'Typed API agreement shared across boundaries.' },
  { word: 'context', kind: 'domain', scopes: ['global'], meaning: 'Typed runtime request or execution context.' },
  { word: 'construction', kind: 'platform', scopes: ['global'], meaning: 'Native object creation expression.' },
  { word: 'create', kind: 'action', scopes: ['global'], meaning: 'Produce a new owned value or resource.' },
  { word: 'current', kind: 'domain', scopes: ['global'], meaning: 'Current runtime value or time.' },
  { word: 'daemon', kind: 'platform', scopes: ['global'], meaning: 'Operating-system background process.' },
  { word: 'database', kind: 'domain', scopes: ['global'], meaning: 'Persistent structured storage.' },
  { word: 'date', kind: 'platform', scopes: ['global'], meaning: 'Native JavaScript Date API that product code must avoid.' },
  { word: 'declaration', kind: 'domain', scopes: ['global'], meaning: 'Named TypeScript construct.' },
  { word: 'default', kind: 'grammar', scopes: ['global'], meaning: 'Language-level default export or default branch.' },
  { word: 'delete', kind: 'action', scopes: ['global'], meaning: 'Remove an owned value or resource.' },
  { word: 'dayjs', kind: 'platform', scopes: ['global'], meaning: 'Approved Brioela date and time library.' },
  { word: 'domain', kind: 'domain', scopes: ['global'], meaning: 'A meaningful product or system concept.' },
  { word: 'drizzle', kind: 'platform', scopes: ['global'], meaning: 'The only approved database language in product runtime code.' },
  { word: 'durable', kind: 'platform', scopes: ['global'], meaning: 'Cloudflare Durable Object persistence/runtime concept.' },
  { word: 'effect', kind: 'domain', scopes: ['global'], meaning: 'Side effect or runtime impact.' },
  { word: 'empty', kind: 'predicate', scopes: ['global'], meaning: 'Having no items.' },
  { word: 'enforce', kind: 'action', scopes: ['global'], meaning: 'Block code that violates a guard rule.' },
  { word: 'entries', kind: 'domain', scopes: ['global'], meaning: 'Many ordered manifest or journal records.' },
  { word: 'entry', kind: 'domain', scopes: ['global'], meaning: 'One ordered manifest or journal record.' },
  { word: 'email', kind: 'domain', scopes: ['global'], meaning: 'Email address or email delivery concept.' },
  { word: 'env', kind: 'platform', scopes: ['global'], meaning: 'Runtime environment binding surface.' },
  { word: 'entity', kind: 'domain', scopes: ['global'], meaning: 'Object being inspected by a type guard.' },
  { word: 'environment', kind: 'domain', scopes: ['global'], meaning: 'Typed runtime environment shape.' },
  { word: 'error', kind: 'domain', scopes: ['global'], meaning: 'Named failure state.' },
  { word: 'epoch', kind: 'platform', scopes: ['global'], meaning: 'Unix epoch timestamp representation.' },
  { word: 'event', kind: 'role', scopes: ['global'], meaning: 'Fact that happened in time.' },
  { word: 'events', kind: 'role', scopes: ['global'], meaning: 'Many facts that happened in time.' },
  { word: 'exists', kind: 'predicate', scopes: ['global'], meaning: 'Present in storage or runtime.' },
  { word: 'expected', kind: 'predicate', scopes: ['global'], meaning: 'Required by a generated check.' },
  { word: 'expression', kind: 'platform', scopes: ['global'], meaning: 'TypeScript AST expression node.' },
  { word: 'export', kind: 'action', scopes: ['global'], meaning: 'Expose a module member.' },
  { word: 'file', kind: 'domain', scopes: ['global'], meaning: 'Repository or filesystem file.' },
  { word: 'files', kind: 'domain', scopes: ['global'], meaning: 'Many repository or filesystem files.' },
  { word: 'first', kind: 'domain', scopes: ['global'], meaning: 'First value in a comparison pair.' },
  { word: 'filter', kind: 'action', scopes: ['global'], meaning: 'Select matching items from a collection.' },
  { word: 'find', kind: 'action', scopes: ['global'], meaning: 'Locate one or more matching things.' },
  { word: 'for', kind: 'grammar', scopes: ['global'], meaning: 'Relation word naming a target use.' },
  { word: 'folder', kind: 'domain', scopes: ['global'], meaning: 'Repository or filesystem directory.' },
  { word: 'format', kind: 'action', scopes: ['global'], meaning: 'Turn structured state into display text.' },
  { word: 'from', kind: 'grammar', scopes: ['global'], meaning: 'Source relation word in imported identifiers.' },
  { word: 'guard', kind: 'domain', scopes: ['global'], meaning: 'Hard gate that blocks illegal code or names.' },
  { word: 'handler', kind: 'role', scopes: ['global'], meaning: 'Entry point that coordinates a runtime operation.' },
  { word: 'has', kind: 'predicate', scopes: ['global'], meaning: 'Owns or contains a value.' },
  { word: 'helper', kind: 'role', scopes: ['global'], meaning: 'Small pure support function with exact ownership.' },
  { word: 'identifier', kind: 'domain', scopes: ['global'], meaning: 'Named code symbol.' },
  { word: 'id', kind: 'domain', scopes: ['global'], meaning: 'Stable identifier.' },
  { word: 'import', kind: 'action', scopes: ['global'], meaning: 'Bring a module member into a file.' },
  { word: 'index', kind: 'role', scopes: ['global'], meaning: 'Scoped barrel export file.' },
  { word: 'initial', kind: 'predicate', scopes: ['global'], meaning: 'Starting state required by a runtime lifecycle.' },
  { word: 'inside', kind: 'grammar', scopes: ['global'], meaning: 'Path or AST containment relationship.' },
  { word: 'invalid', kind: 'predicate', scopes: ['global'], meaning: 'Rejected by a validator or guard.' },
  { word: 'idx', kind: 'platform', scopes: ['global'], meaning: 'Drizzle migration journal index field.' },
  { word: 'is', kind: 'predicate', scopes: ['global'], meaning: 'Boolean identity or state check.' },
  { word: 'imports', kind: 'domain', scopes: ['global'], meaning: 'Generated import declarations.' },
  { word: 'journal', kind: 'domain', scopes: ['global'], meaning: 'Drizzle migration ordering metadata.' },
  { word: 'json', kind: 'platform', scopes: ['global'], meaning: 'JSON serialization format.' },
  { word: 'kind', kind: 'domain', scopes: ['global'], meaning: 'Finite category of a domain object.' },
  { word: 'label', kind: 'domain', scopes: ['global'], meaning: 'Human or system readable name.' },
  { word: 'launch', kind: 'action', scopes: ['global'], meaning: 'Start an operating-system process.' },
  { word: 'launchctl', kind: 'platform', scopes: ['global'], meaning: 'macOS command for controlling launchd services.' },
  { word: 'launchd', kind: 'platform', scopes: ['global'], meaning: 'macOS daemon supervisor.' },
  { word: 'lexicon', kind: 'domain', scopes: ['global'], meaning: 'Controlled vocabulary for Brioela identifiers.' },
  { word: 'list', kind: 'action', scopes: ['global'], meaning: 'Return many items.' },
  { word: 'load', kind: 'action', scopes: ['global'], meaning: 'Read and parse state from storage.' },
  { word: 'log', kind: 'domain', scopes: ['global'], meaning: 'Operational output record.' },
  { word: 'memory', kind: 'domain', scopes: ['global'], meaning: 'Persisted user or agent recall.' },
  { word: 'manifest', kind: 'domain', scopes: ['global'], meaning: 'Generated runtime list of migration artifacts.' },
  { word: 'method', kind: 'platform', scopes: ['global'], meaning: 'Object method call in source code.' },
  { word: 'middleware', kind: 'role', scopes: ['global'], meaning: 'Request pipeline function mounted around routes.' },
  { word: 'migration', kind: 'domain', scopes: ['global'], meaning: 'Versioned database schema change.' },
  { word: 'migrations', kind: 'domain', scopes: ['global'], meaning: 'Many versioned database schema changes.' },
  { word: 'mode', kind: 'domain', scopes: ['global'], meaning: 'Selected operating behavior for a tool or runtime.' },
  { word: 'module', kind: 'domain', scopes: ['global'], meaning: 'Importable code unit.' },
  { word: 'mount', kind: 'action', scopes: ['global'], meaning: 'Attach middleware or routes to an app or router.' },
  { word: 'ms', kind: 'platform', scopes: ['global'], meaning: 'Millisecond timestamp unit.' },
  { word: 'name', kind: 'domain', scopes: ['global'], meaning: 'Human-readable symbol identity.' },
  { word: 'native', kind: 'platform', scopes: ['global'], meaning: 'Built-in runtime API that may need explicit approval.' },
  { word: 'new', kind: 'platform', scopes: ['global'], meaning: 'TypeScript or Drizzle insert-side value shape.' },
  { word: 'next', kind: 'domain', scopes: ['global'], meaning: 'Continuation point after the current ordered slice.' },
  { word: 'nearby', kind: 'grammar', scopes: ['global'], meaning: 'Adjacent or parent-scope proximity relationship.' },
  { word: 'node', kind: 'platform', scopes: ['global'], meaning: 'TypeScript AST node or Node.js runtime concept.' },
  { word: 'now', kind: 'domain', scopes: ['global'], meaning: 'Current point in time.' },
  { word: 'null', kind: 'grammar', scopes: ['global'], meaning: 'Intentional empty value.' },
  { word: 'own', kind: 'predicate', scopes: ['global'], meaning: 'Directly held by an object, not inherited.' },
  { word: 'parse', kind: 'action', scopes: ['global'], meaning: 'Convert unknown input into a validated shape.' },
  { word: 'parent', kind: 'domain', scopes: ['global'], meaning: 'Containing scope or folder.' },
  { word: 'path', kind: 'domain', scopes: ['global'], meaning: 'Repository, URL, or filesystem location.' },
  { word: 'page', kind: 'domain', scopes: ['global'], meaning: 'Bounded ordered slice returned from a larger collection.' },
  { word: 'pending', kind: 'predicate', scopes: ['global'], meaning: 'Waiting to be processed.' },
  { word: 'plist', kind: 'platform', scopes: ['global'], meaning: 'macOS property list file.' },
  { word: 'policy', kind: 'role', scopes: ['global'], meaning: 'One enforceable guard rule.' },
  { word: 'policies', kind: 'role', scopes: ['global'], meaning: 'Many enforceable guard rules.' },
  { word: 'predicate', kind: 'domain', scopes: ['global'], meaning: 'Boolean meaning word.' },
  { word: 'prefix', kind: 'domain', scopes: ['global'], meaning: 'Leading text segment used for matching.' },
  { word: 'print', kind: 'action', scopes: ['global'], meaning: 'Emit diagnostic text.' },
  { word: 'product', kind: 'domain', scopes: ['global'], meaning: 'Runtime application code, not tooling.' },
  { word: 'property', kind: 'domain', scopes: ['global'], meaning: 'Named object field inspected by a type guard.' },
  { word: 'raw', kind: 'domain', scopes: ['global'], meaning: 'Unparsed or uncontracted runtime content.' },
  { word: 'read', kind: 'action', scopes: ['global'], meaning: 'Load without mutating.' },
  { word: 'ready', kind: 'predicate', scopes: ['global'], meaning: 'Initialized and available for runtime use.' },
  { word: 'record', kind: 'action', scopes: ['global'], meaning: 'Persist a fact.' },
  { word: 'records', kind: 'domain', scopes: ['global'], meaning: 'Many stored or generated entries.' },
  { word: 'repo', kind: 'domain', scopes: ['global'], meaning: 'Repository-relative identity.' },
  { word: 'repository', kind: 'role', scopes: ['global'], meaning: 'Persistence access boundary using approved database surfaces.' },
  { word: 'resolve', kind: 'action', scopes: ['global'], meaning: 'Turn an input into a canonical target.' },
  { word: 'role', kind: 'domain', scopes: ['global'], meaning: 'File or identifier responsibility category.' },
  { word: 'root', kind: 'domain', scopes: ['global'], meaning: 'Top of a workspace or scoped tree.' },
  { word: 'route', kind: 'role', scopes: ['global'], meaning: 'HTTP route definition surface.' },
  { word: 'routes', kind: 'role', scopes: ['global'], meaning: 'Grouped HTTP route definitions.' },
  { word: 'rpc', kind: 'role', scopes: ['global'], meaning: 'Typed callable boundary between agents or processes.' },
  { word: 'run', kind: 'action', scopes: ['global'], meaning: 'Execute a command, handler, or process.' },
  { word: 'schema', kind: 'role', scopes: ['global'], meaning: 'Validated shape or Drizzle table definition boundary.' },
  { word: 'scope', kind: 'domain', scopes: ['global'], meaning: 'Bounded ownership area.' },
  { word: 'script', kind: 'platform', scopes: ['global'], meaning: 'Executable source file or TypeScript script kind.' },
  { word: 'select', kind: 'action', scopes: ['global'], meaning: 'Choose matching items.' },
  { word: 'second', kind: 'domain', scopes: ['global'], meaning: 'Second value in a comparison pair.' },
  { word: 'source', kind: 'domain', scopes: ['global'], meaning: 'Origin of code, data, or an AST node.' },
  { word: 'smoke', kind: 'domain', scopes: ['global'], meaning: 'Cheap deterministic readiness verification after a migration.' },
  { word: 'sql', kind: 'platform', scopes: ['global'], meaning: 'SQL migration artifact generated by Drizzle.' },
  { word: 'sqlite', kind: 'platform', scopes: ['global'], meaning: 'Private Durable Object SQLite storage layer under Drizzle.' },
  { word: 'state', kind: 'domain', scopes: ['global'], meaning: 'Runtime state held by an actor or process.' },
  { word: 'stale', kind: 'predicate', scopes: ['global'], meaning: 'Out of sync with generated source of truth.' },
  { word: 'status', kind: 'domain', scopes: ['global'], meaning: 'Operational state summary.' },
  { word: 'storage', kind: 'domain', scopes: ['global'], meaning: 'Persistence substrate.' },
  { word: 'string', kind: 'platform', scopes: ['global'], meaning: 'Primitive text value.' },
  { word: 'suffix', kind: 'domain', scopes: ['global'], meaning: 'Trailing name segment that identifies a role or pattern.' },
  { word: 'tail', kind: 'action', scopes: ['global'], meaning: 'Follow log output.' },
  { word: 'tag', kind: 'domain', scopes: ['global'], meaning: 'Drizzle migration journal tag.' },
  { word: 'target', kind: 'domain', scopes: ['global'], meaning: 'Destination or second value in a transformation.' },
  { word: 'text', kind: 'platform', scopes: ['global'], meaning: 'Text storage column or primitive text.' },
  { word: 'to', kind: 'grammar', scopes: ['global'], meaning: 'Destination relation word in mapper names.' },
  { word: 'type', kind: 'role', scopes: ['global'], meaning: 'Compile-time shape definition.' },
  { word: 'typescript', kind: 'platform', scopes: ['global'], meaning: 'TypeScript language/runtime tooling.' },
  { word: 'valid', kind: 'predicate', scopes: ['global'], meaning: 'Accepted by a parser or policy.' },
  { word: 'validate', kind: 'action', scopes: ['global'], meaning: 'Check a value against a rule.' },
  { word: 'v1', kind: 'platform', scopes: ['global'], meaning: 'Version one API route namespace.' },
  { word: 'violation', kind: 'domain', scopes: ['global'], meaning: 'Specific guard failure.' },
  { word: 'violations', kind: 'domain', scopes: ['global'], meaning: 'Many specific guard failures.' },
  { word: 'variables', kind: 'platform', scopes: ['global'], meaning: 'Hono typed context variable container key.' },
  { word: 'visit', kind: 'action', scopes: ['global'], meaning: 'Walk a TypeScript AST node.' },
  { word: 'watch', kind: 'action', scopes: ['global'], meaning: 'Continuously observe and rerun checks.' },
  { word: 'with', kind: 'grammar', scopes: ['global'], meaning: 'Association relation word in helper names.' },
  { word: 'word', kind: 'domain', scopes: ['global'], meaning: 'Smallest controlled naming unit.' },
  { word: 'workspace', kind: 'domain', scopes: ['global'], meaning: 'Checked repository root.' },
  { word: 'write', kind: 'action', scopes: ['global'], meaning: 'Persist or emit state.' },
]
