import type { LexiconWord } from '../_types'

export const productLexicon: LexiconWord[] = [
  { word: 'alarm', kind: 'domain', scopes: ['product'], meaning: 'Brain scheduled wake or user-facing reminder work item.' },
  { word: 'alarms', kind: 'domain', scopes: ['product'], meaning: 'Many Brain scheduled wake or reminder work items.' },
  { word: 'bela', kind: 'domain', scopes: ['product'], meaning: 'Brioela grocery delivery surface.' },
  { word: 'brain', kind: 'domain', scopes: ['product'], meaning: 'Private context, memory, and reasoning substrate for Brioela.' },
  { word: 'captured', kind: 'domain', scopes: ['product'], meaning: 'Time when a user event actually happened, which may differ from storage ingestion time.' },
  { word: 'constraint', kind: 'domain', scopes: ['product'], meaning: 'Safety or preference rule such as allergy, intolerance, dislike, identity, or boycott.' },
  { word: 'constraints', kind: 'domain', scopes: ['product'], meaning: 'Many safety or preference rules owned by the Brain.' },
  { word: 'confirmation', kind: 'domain', scopes: ['product'], meaning: 'Constraint verification workflow that records whether user or behavior confirmed a safety rule.' },
  { word: 'cooking', kind: 'domain', scopes: ['product'], meaning: 'Live cooking session experience.' },
  { word: 'food', kind: 'domain', scopes: ['product'], meaning: 'Edible domain concept across Brioela.' },
  { word: 'ingested', kind: 'domain', scopes: ['product'], meaning: 'Time when an event was written into Brain storage.' },
  { word: 'ingredient', kind: 'domain', scopes: ['product'], meaning: 'Recipe or grocery item used for cooking.' },
  { word: 'meal', kind: 'domain', scopes: ['product'], meaning: 'Planned or cooked eating occasion.' },
  { word: 'menu', kind: 'domain', scopes: ['product'], meaning: 'Restaurant or household food choice surface.' },
  { word: 'mira', kind: 'domain', scopes: ['product'], meaning: 'Shared Brioela voice/video agent presence with injected context and stimuli.' },
  { word: 'nutrition', kind: 'domain', scopes: ['product'], meaning: 'Food health and nutrient meaning.' },
  { word: 'personality', kind: 'domain', scopes: ['product'], meaning: 'Synthesized user trait memory inferred from durable evidence.' },
  { word: 'phase', kind: 'domain', scopes: ['product'], meaning: 'Migration rollout stage such as expand, backfill, verify, or contract.' },
  { word: 'recipe', kind: 'domain', scopes: ['product'], meaning: 'Structured cooking instructions and ingredients.' },
  { word: 'recipes', kind: 'domain', scopes: ['product'], meaning: 'Many user-owned structured cooking records.' },
  { word: 'readiness', kind: 'domain', scopes: ['product'], meaning: 'Verified ability for a runtime area to safely proceed.' },
  { word: 'results', kind: 'domain', scopes: ['product'], meaning: 'Many recorded outcomes from a product verification or smoke run.' },
  { word: 'risk', kind: 'domain', scopes: ['product'], meaning: 'Migration rollout danger level used by Brain readiness policy.' },
  { word: 'runs', kind: 'domain', scopes: ['product'], meaning: 'Many executions of a product operation such as a migration.' },
  { word: 'scheduled', kind: 'predicate', scopes: ['product'], meaning: 'Planned to run at a future Brain wake time.' },
  { word: 'session', kind: 'domain', scopes: ['product'], meaning: 'One bounded user, agent, background, or cooking interaction.' },
  { word: 'sessions', kind: 'domain', scopes: ['product'], meaning: 'Many bounded user, agent, background, or cooking interactions.' },
  { word: 'shopper', kind: 'domain', scopes: ['product'], meaning: 'Grocery shopping assistant or human-like shopping flow.' },
  { word: 'skill', kind: 'domain', scopes: ['product'], meaning: 'Reusable procedural instruction set learned or shipped for the Brain.' },
  { word: 'skills', kind: 'domain', scopes: ['product'], meaning: 'Many reusable procedural instruction sets available to the Brain.' },
  { word: 'stimulus', kind: 'domain', scopes: ['product'], meaning: 'Observed context input feeding Mira or Brain.' },
  { word: 'stimuli', kind: 'domain', scopes: ['product'], meaning: 'Multiple observed context inputs feeding Mira or Brain.' },
  { word: 'turn', kind: 'domain', scopes: ['product'], meaning: 'One ordered message or tool exchange within a session.' },
  { word: 'turns', kind: 'domain', scopes: ['product'], meaning: 'Many ordered messages or tool exchanges within a session.' },
  { word: 'user', kind: 'domain', scopes: ['product'], meaning: 'Person using Brioela.' },
  { word: 'version', kind: 'domain', scopes: ['product'], meaning: 'One numbered product schema or skill history revision.' },
  { word: 'versions', kind: 'domain', scopes: ['product'], meaning: 'Many numbered product schema or skill history revisions.' },
]
