import { access } from 'node:fs/promises'
import {
	brainMigrationSqlFolderPath,
	resolveWorkspacePath,
} from './brain.migration.manifest.paths.helper'
import { readBrainMigrationJournal } from './read.brain.migration.journal.helper'

export async function createBrainMigrationManifest(workspaceRoot: string): Promise<string> {
	const journal = await readBrainMigrationJournal(workspaceRoot)
	const entries = [...journal.entries].sort((source, target) => source.idx - target.idx)

	for (const entry of entries) {
		await access(resolveWorkspacePath(workspaceRoot, `${brainMigrationSqlFolderPath}/${entry.tag}.sql`))
	}

	const migrationImports = entries
		.map((entry) => `import migration${formatMigrationIndex(entry.idx)} from '@/agents/brain/drizzle/${entry.tag}.sql?raw'`)
		.join('\n')

	const migrationRecords = entries
		.map((entry) => `\t\tm${formatMigrationIndex(entry.idx)}: migration${formatMigrationIndex(entry.idx)},`)
		.join('\n')

	return `// Generated by Brioela Brain Migration Manifest. Do not edit by hand.\nimport journal from '@/agents/brain/drizzle/meta/_journal.json'\n${migrationImports}\nimport type { BrainMigrationBundle } from '@/agents/brain/_migrations/brain.migration.schema'\n\nexport const brainMigrationBundle: BrainMigrationBundle = {\n\tjournal,\n\tmigrations: {\n${migrationRecords}\n\t},\n}\n`
}

function formatMigrationIndex(index: number): string {
	return index.toString().padStart(4, '0')
}
