import { access, readFile } from 'node:fs/promises'
import {
	brainMigrationSqlFolderPath,
	resolveWorkspacePath,
} from './brain.migration.manifest.paths.helper'
import { readBrainMigrationJournal } from './read.brain.migration.journal.helper'

export async function createBrainMigrationManifest(workspaceRoot: string): Promise<string> {
	const journal = await readBrainMigrationJournal(workspaceRoot)
	const entries = [...journal.entries].sort((source, target) => source.idx - target.idx)

	for (const entry of entries) {
		await access(resolveWorkspacePath(workspaceRoot, `${brainMigrationSqlFolderPath}/${entry.tag}.sql`))
	}

	const migrationConstants = await Promise.all(
		entries.map(async (entry) => {
			const migrationSql = await readFile(
				resolveWorkspacePath(workspaceRoot, `${brainMigrationSqlFolderPath}/${entry.tag}.sql`),
				'utf8',
			)

			return `const migration${formatMigrationIndex(entry.idx)} = ${JSON.stringify(migrationSql)}`
		}),
	)

	const migrationValues = migrationConstants.join('\n')
	const journalValue = `const journal = ${JSON.stringify(journal)}`

	const migrationRecords = entries
		.map((entry) => `\t\tm${formatMigrationIndex(entry.idx)}: migration${formatMigrationIndex(entry.idx)},`)
		.join('\n')

	return `// Generated by Brioela Brain Migration Manifest. Do not edit by hand.\nimport type { BrainMigrationBundle } from '@/agents/brain/_migrations/migration.schema'\n\n${journalValue}\n${migrationValues}\n\nexport const brainMigrationBundle: BrainMigrationBundle = {\n\tjournal,\n\tmigrations: {\n${migrationRecords}\n\t},\n}\n`
}

function formatMigrationIndex(index: number): string {
	return index.toString().padStart(4, '0')
}
