import type { LexiconWord } from '../../_types'

export const toolsReadingGateLexicon: LexiconWord[] = [
  { word: 'reading', kind: 'domain', scopes: ['tools'], meaning: 'Proof-of-reading concept owned by the reading gate.' },
  { word: 'gate', kind: 'domain', scopes: ['tools'], meaning: 'Reading gate — proof-of-reading enforcement system.' },
  { word: 'hash', kind: 'domain', scopes: ['tools'], meaning: 'SHA-256 content digest proving which bytes were served.' },
  { word: 'fresh', kind: 'predicate', scopes: ['tools'], meaning: 'Read proof still inside the ttl window and hash-current.' },
  { word: 'socket', kind: 'platform', scopes: ['tools'], meaning: 'Unix domain socket transport for the gate daemon.' },
  { word: 'pid', kind: 'platform', scopes: ['tools'], meaning: 'Operating-system process id.' },
  { word: 'url', kind: 'platform', scopes: ['tools'], meaning: 'Parsed request locator for socket routing.' },
  { word: 'content', kind: 'domain', scopes: ['tools'], meaning: 'File bytes streamed through the gate into agent context.' },
  { word: 'bytes', kind: 'domain', scopes: ['tools'], meaning: 'Byte count of content served by the gate.' },
  { word: 'serve', kind: 'action', scopes: ['tools'], meaning: 'Listen and respond on a transport.' },
  { word: 'verdict', kind: 'domain', scopes: ['tools'], meaning: 'The single authoritative guard judgment: clean or blocked.' },
  { word: 'receipt', kind: 'domain', scopes: ['tools'], meaning: 'Signed proof that the board was clean for an exact diff hash.' },
  { word: 'heartbeat', kind: 'domain', scopes: ['tools'], meaning: 'Signed liveness proof written by the gate daemon on an interval.' },
  { word: 'board', kind: 'domain', scopes: ['tools'], meaning: 'Persistent violations state owned by the gate daemon.' },
  { word: 'tamper', kind: 'domain', scopes: ['tools'], meaning: 'Detected change to guard machinery — clears only by human ritual.' },
  { word: 'rule', kind: 'domain', scopes: ['tools'], meaning: 'Identifier of one guard policy that produced a violation.' },
  { word: 'line', kind: 'domain', scopes: ['tools'], meaning: 'Source line position of a violation.' },
  { word: 'suggestion', kind: 'domain', scopes: ['tools'], meaning: 'Inline fix guidance attached to a violation.' },
  { word: 'suggestions', kind: 'domain', scopes: ['tools'], meaning: 'Many inline fix guidance entries.' },
  { word: 'distance', kind: 'domain', scopes: ['tools'], meaning: 'Edit distance between an unknown word and known vocabulary.' },
  { word: 'distances', kind: 'domain', scopes: ['tools'], meaning: 'Edit distance working values.' },
  { word: 'diff', kind: 'domain', scopes: ['tools'], meaning: 'Git change set, hashed to bind receipts to exact work.' },
  { word: 'sign', kind: 'action', scopes: ['tools'], meaning: 'Produce an ed25519 signature over gate state.' },
  { word: 'signature', kind: 'domain', scopes: ['tools'], meaning: 'ed25519 signature bytes encoded base64.' },
  { word: 'public', kind: 'platform', scopes: ['tools'], meaning: 'Shareable half of the gate keypair.' },
  { word: 'private', kind: 'platform', scopes: ['tools'], meaning: 'Root-only half of the gate keypair.' },
  { word: 'flag', kind: 'domain', scopes: ['tools'], meaning: 'GUARD-RED marker file raised while the board is red.' },
  { word: 'red', kind: 'predicate', scopes: ['tools'], meaning: 'Board state with violations or tamper — nothing lands.' },
  { word: 'stream', kind: 'domain', scopes: ['tools'], meaning: 'Live subscriber channel for gate events.' },
  { word: 'streams', kind: 'domain', scopes: ['tools'], meaning: 'Many live subscriber channels.' },
  { word: 'git', kind: 'platform', scopes: ['tools'], meaning: 'Version control chokepoint the verdict hooks into.' },
  { word: 'fixed', kind: 'predicate', scopes: ['tools'], meaning: 'Violation present on the previous board and gone now.' },
  { word: 'previous', kind: 'domain', scopes: ['tools'], meaning: 'Prior board state used for delta attribution.' },
  { word: 'hooks', kind: 'platform', scopes: ['tools'], meaning: 'Git hooks path the gate installs its pre-commit wall into.' },
]
