import type { LexiconWord } from '../../_types'

export const toolsReadingGateLexicon: LexiconWord[] = [
  { word: 'reading', kind: 'domain', scopes: ['tools'], meaning: 'Proof-of-reading concept owned by the reading gate.' },
  { word: 'gate', kind: 'domain', scopes: ['tools'], meaning: 'Reading gate — proof-of-reading enforcement system.' },
  { word: 'hash', kind: 'domain', scopes: ['tools'], meaning: 'SHA-256 content digest proving which bytes were served.' },
  { word: 'fresh', kind: 'predicate', scopes: ['tools'], meaning: 'Read proof still inside the ttl window and hash-current.' },
  { word: 'socket', kind: 'platform', scopes: ['tools'], meaning: 'Unix domain socket transport for the gate daemon.' },
  { word: 'pid', kind: 'platform', scopes: ['tools'], meaning: 'Operating-system process id.' },
  { word: 'url', kind: 'platform', scopes: ['tools'], meaning: 'Parsed request locator for socket routing.' },
  { word: 'content', kind: 'domain', scopes: ['tools'], meaning: 'File bytes streamed through the gate into agent context.' },
  { word: 'bytes', kind: 'domain', scopes: ['tools'], meaning: 'Byte count of content served by the gate.' },
  { word: 'serve', kind: 'action', scopes: ['tools'], meaning: 'Listen and respond on a transport.' },
  { word: 'verdict', kind: 'domain', scopes: ['tools'], meaning: 'The single authoritative guard judgment: clean or blocked.' },
  { word: 'receipt', kind: 'domain', scopes: ['tools'], meaning: 'Signed proof that the board was clean for an exact diff hash.' },
  { word: 'heartbeat', kind: 'domain', scopes: ['tools'], meaning: 'Signed liveness proof written by the gate daemon on an interval.' },
  { word: 'board', kind: 'domain', scopes: ['tools'], meaning: 'Persistent violations state owned by the gate daemon.' },
  { word: 'tamper', kind: 'domain', scopes: ['tools'], meaning: 'Detected change to guard machinery — clears only by human ritual.' },
  { word: 'rule', kind: 'domain', scopes: ['tools'], meaning: 'Identifier of one guard policy that produced a violation.' },
  { word: 'line', kind: 'domain', scopes: ['tools'], meaning: 'Source line position of a violation.' },
  { word: 'suggestion', kind: 'domain', scopes: ['tools'], meaning: 'Inline fix guidance attached to a violation.' },
  { word: 'suggestions', kind: 'domain', scopes: ['tools'], meaning: 'Many inline fix guidance entries.' },
  { word: 'distance', kind: 'domain', scopes: ['tools'], meaning: 'Edit distance between an unknown word and known vocabulary.' },
  { word: 'distances', kind: 'domain', scopes: ['tools'], meaning: 'Edit distance working values.' },
  { word: 'diff', kind: 'domain', scopes: ['tools'], meaning: 'Git change set, hashed to bind receipts to exact work.' },
  { word: 'sign', kind: 'action', scopes: ['tools'], meaning: 'Produce an ed25519 signature over gate state.' },
  { word: 'signature', kind: 'domain', scopes: ['tools'], meaning: 'ed25519 signature bytes encoded base64.' },
  { word: 'public', kind: 'platform', scopes: ['tools'], meaning: 'Shareable half of the gate keypair.' },
  { word: 'private', kind: 'platform', scopes: ['tools'], meaning: 'Root-only half of the gate keypair.' },
  { word: 'flag', kind: 'domain', scopes: ['tools'], meaning: 'GUARD-RED marker file raised while the board is red.' },
  { word: 'red', kind: 'predicate', scopes: ['tools'], meaning: 'Board state with violations or tamper — nothing lands.' },
  { word: 'stream', kind: 'domain', scopes: ['tools'], meaning: 'Live subscriber channel for gate events.' },
  { word: 'streams', kind: 'domain', scopes: ['tools'], meaning: 'Many live subscriber channels.' },
  { word: 'git', kind: 'platform', scopes: ['tools'], meaning: 'Version control chokepoint the verdict hooks into.' },
  { word: 'fixed', kind: 'predicate', scopes: ['tools'], meaning: 'Violation present on the previous board and gone now.' },
  { word: 'previous', kind: 'domain', scopes: ['tools'], meaning: 'Prior board state used for delta attribution.' },
  { word: 'hooks', kind: 'platform', scopes: ['tools'], meaning: 'Git hooks path the gate installs its pre-commit wall into.' },
  { word: 'hook', kind: 'platform', scopes: ['tools'], meaning: 'One harness hook invocation of the verdict (exit 2 feedback).' },
  { word: 'added', kind: 'predicate', scopes: ['tools'], meaning: 'Violation newly present versus the previous board.' },
  { word: 'kept', kind: 'predicate', scopes: ['tools'], meaning: 'Violation present on both the previous and current board.' },
  { word: 'changed', kind: 'predicate', scopes: ['tools'], meaning: 'Path touched by a filesystem event.' },
  { word: 'blocked', kind: 'predicate', scopes: ['tools'], meaning: 'Verdict state that stops anything from landing.' },
  { word: 'green', kind: 'predicate', scopes: ['tools'], meaning: 'Board state with zero violations and no tamper.' },
  { word: 'forged', kind: 'predicate', scopes: ['tools'], meaning: 'Write that pretended to be the daemon and must be rejected.' },
  { word: 'ignored', kind: 'predicate', scopes: ['tools'], meaning: 'Path excluded from watching.' },
  { word: 'elapsed', kind: 'domain', scopes: ['tools'], meaning: 'Milliseconds a guard sweep took.' },
  { word: 'column', kind: 'domain', scopes: ['tools'], meaning: 'Source column position of a violation.' },
  { word: 'limit', kind: 'domain', scopes: ['tools'], meaning: 'Maximum entries returned by a gate query.' },
  { word: 'part', kind: 'domain', scopes: ['tools'], meaning: 'One path segment.' },
  { word: 'parts', kind: 'domain', scopes: ['tools'], meaning: 'Many path segments.' },
  { word: 'pattern', kind: 'domain', scopes: ['tools'], meaning: 'Regular expression a gate formatter matches against.' },
  { word: 'report', kind: 'domain', scopes: ['tools'], meaning: 'One smoke-check verdict line.' },
  { word: 'roots', kind: 'domain', scopes: ['tools'], meaning: 'Workspace top folders the daemon watches.' },
  { word: 'runs', kind: 'domain', scopes: ['tools'], meaning: 'Violation totals of recent verdict sweeps.' },
  { word: 'exit', kind: 'platform', scopes: ['tools'], meaning: 'Process exit code carrying the verdict to any harness.' },
  { word: 'timer', kind: 'platform', scopes: ['tools'], meaning: 'Interval handle for the heartbeat loop.' },
  { word: 'start', kind: 'action', scopes: ['tools'], meaning: 'ReadableStream lifecycle method (platform API name).' },
  { word: 'cancel', kind: 'action', scopes: ['tools'], meaning: 'ReadableStream lifecycle method (platform API name).' },
  { word: 'controller', kind: 'platform', scopes: ['tools'], meaning: 'ReadableStream controller (platform API name).' },
  { word: 'bold', kind: 'platform', scopes: ['tools'], meaning: 'ANSI display style for the watch terminal.' },
  { word: 'dim', kind: 'platform', scopes: ['tools'], meaning: 'ANSI display style for the watch terminal.' },
  { word: 'yellow', kind: 'platform', scopes: ['tools'], meaning: 'ANSI display color for the watch terminal.' },
  { word: 'reset', kind: 'platform', scopes: ['tools'], meaning: 'ANSI style reset for the watch terminal.' },
  { word: 'stopped', kind: 'predicate', scopes: ['tools'], meaning: 'Indicates a process or daemon has stopped.' },
  { word: 'out', kind: 'domain', scopes: ['tools'], meaning: 'Standard output logs or general output.' },
  { word: 'err', kind: 'domain', scopes: ['tools'], meaning: 'Standard error logs or error references.' },
  { word: 'process', kind: 'domain', scopes: ['tools'], meaning: 'Operating system process reference.' },
  { word: 'dir', kind: 'domain', scopes: ['tools'], meaning: 'Directory path reference.' },
  { word: 'results', kind: 'domain', scopes: ['tools'], meaning: 'Collection of search or execution outcomes.' },
  { word: 'full', kind: 'predicate', scopes: ['tools'], meaning: 'Indicates a complete or full path/dataset.' },
  { word: 'stat', kind: 'domain', scopes: ['tools'], meaning: 'File status metadata object from fs.stat.' },
  { word: 'get', kind: 'action', scopes: ['tools'], meaning: 'Retrieve or fetch a resource or file list.' },
  { word: 'protected', kind: 'predicate', scopes: ['tools'], meaning: 'Indicates files covered by security policies.' },
  { word: 'deploy', kind: 'domain', scopes: ['tools'], meaning: 'Deploy configuration or process.' },
  { word: 'post', kind: 'predicate', scopes: ['tools'], meaning: 'State of files after an action is run.' },
  { word: 'args', kind: 'domain', scopes: ['tools'], meaning: 'Command line arguments array.' },
  { word: 'f', kind: 'domain', scopes: ['tools'], meaning: 'Loop variable representing a file path.' },
]
