import React, { useMemo } from 'react';
import { View, Text } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { KeyboardAwareScrollView } from 'react-native-keyboard-controller';
import { BackButton } from '@/components/ui/back-button';

type AgreementSection = {
  title: string;
  body: string;
};

export default function OurAgreementsScreen(): React.ReactElement {
  const sections = useMemo<AgreementSection[]>(() => {
    return [
      {
        title: 'OUR AGREEMENTS',
        body: 'THESE AGREEMENTS GOVERN YOUR ACCESS TO AND USE OF SCHNL, INCLUDING ANY FEATURES THAT ALLOW YOU TO VIEW BALANCES, INITIATE TRANSACTIONS, RECEIVE FUNDS, REQUEST STATEMENTS, USE CARDS, OR ACCESS OTHER FINANCIAL SERVICES.\n\nBY CREATING AN ACCOUNT, ACCESSING, OR USING SCHNL, YOU CONFIRM THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE AGREEMENTS. IF YOU DO NOT AGREE, DO NOT USE SCHNL.\n\nSCHNL MAY UPDATE THESE AGREEMENTS FROM TIME TO TIME. WE WILL POST UPDATED TERMS IN-APP. YOUR CONTINUED USE OF SCHNL AFTER AN UPDATE MEANS YOU ACCEPT THE UPDATED TERMS.',
      },
      {
        title: '1. DEFINITIONS',
        body: '“SCHNL” MEANS THE APPLICATION, WEBSITE, SERVICES, AND RELATED FEATURES PROVIDED BY SCHNL.\n\n“YOU” OR “USER” MEANS THE INDIVIDUAL USING SCHNL, INCLUDING ANY PERSON WHO CREATES AN ACCOUNT OR INITIATES A TRANSACTION.\n\n“ACCOUNT” MEANS YOUR SCHNL PROFILE AND ANY CONNECTED FEATURES, INCLUDING BALANCES, TRANSACTIONS, CARDS, STATEMENTS, AND SETTINGS, IF AVAILABLE TO YOU.\n\n“FUNDS” MEANS FIAT CURRENCY OR OTHER VALUE THAT YOU LOAD, RECEIVE, HOLD, OR TRANSFER USING SCHNL.\n\n“PROVIDER” MEANS ANY BANK, CARD ISSUER, PAYMENT PROCESSOR, OR THIRD PARTY THAT HELPS DELIVER FEATURES OR MEETS REGULATORY REQUIREMENTS.',
      },
      {
        title: '2. ELIGIBILITY',
        body: 'YOU MUST BE AT LEAST THE AGE OF MAJORITY IN YOUR JURISDICTION AND HAVE THE LEGAL CAPACITY TO ENTER INTO THESE AGREEMENTS.\n\nYOU MUST PROVIDE ACCURATE, COMPLETE, AND CURRENT INFORMATION AND PROMPTLY UPDATE IT IF IT CHANGES.\n\nWE MAY REQUIRE IDENTITY VERIFICATION, SOURCE-OF-FUNDS INFORMATION, SANCTIONS SCREENING, AND OTHER CHECKS TO COMPLY WITH LAW AND PROVIDER REQUIREMENTS.\n\nWE MAY REFUSE, SUSPEND, LIMIT, OR TERMINATE ACCESS IF YOU FAIL TO MEET ELIGIBILITY OR VERIFICATION REQUIREMENTS, OR IF REQUIRED BY LAW, REGULATORS, OR PROVIDERS.',
      },
      {
        title: '3. SERVICES',
        body: 'SCHNL MAY OFFER FEATURES SUCH AS VIEWING ACCOUNT INFORMATION, TRANSACTION HISTORY, BALANCES, TRANSFERS, PAYMENTS, RECEIVING FUNDS, CARD FEATURES, AND GENERATING STATEMENTS. AVAILABILITY MAY VARY BY REGION, USER TYPE, AND PROVIDER SUPPORT.\n\nWE MAY MODIFY, ADD, OR REMOVE FEATURES AT ANY TIME, INCLUDING FOR COMPLIANCE OR SECURITY REASONS.\n\nYOU AUTHORIZE SCHNL AND ITS PROVIDERS TO PROCESS TRANSACTIONS YOU INITIATE AND TO DISPLAY TRANSACTION HISTORY AND STATEMENTS BASED ON AVAILABLE DATA.',
      },
      {
        title: '4. FEES',
        body: 'SCHNL MAY CHARGE FEES FOR CERTAIN FEATURES. WHERE FEES APPLY, THEY WILL BE DISCLOSED IN-APP BEFORE YOU CONFIRM A TRANSACTION OR ACTION.\n\nTHIRD-PARTY FEES MAY ALSO APPLY, INCLUDING BANK FEES, NETWORK FEES, OR PROVIDER CHARGES. THESE FEES ARE NOT CONTROLLED BY SCHNL AND MAY CHANGE AT ANY TIME.\n\nALL FEES ARE NON-REFUNDABLE EXCEPT WHERE REQUIRED BY LAW OR EXPRESSLY STATED OTHERWISE IN-APP.',
      },
      {
        title: '5. PRIVACY',
        body: 'SCHNL PROCESSES PERSONAL DATA TO PROVIDE THE SERVICES, MEET LEGAL AND REGULATORY OBLIGATIONS, PREVENT FRAUD, AND IMPROVE THE PRODUCT.\n\nWE MAY SHARE DATA WITH PROVIDERS FOR IDENTITY VERIFICATION, PAYMENT PROCESSING, CUSTOMER SUPPORT, SECURITY, AND COMPLIANCE PURPOSES.\n\nYOU AUTHORIZE THIS PROCESSING AND SHARING BY USING SCHNL.\n\nADDITIONAL DETAILS MAY BE PROVIDED IN OUR PRIVACY NOTICE, IF AVAILABLE IN-APP OR ON OUR WEBSITE.',
      },
      {
        title: '6. LIMITATIONS OF LIABILITY',
        body: 'TO THE MAXIMUM EXTENT PERMITTED BY LAW, SCHNL AND ITS PROVIDERS WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA, OR GOODWILL, ARISING OUT OF OR RELATED TO YOUR USE OF SCHNL.\n\nSCHNL IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. TO THE EXTENT PERMITTED BY LAW, SCHNL DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED.\n\nIF SCHNL IS FOUND LIABLE, OUR TOTAL LIABILITY FOR ALL CLAIMS WILL BE LIMITED TO THE GREATER OF (A) THE FEES YOU PAID TO SCHNL FOR THE RELEVANT FEATURE IN THE THREE (3) MONTHS BEFORE THE EVENT GIVING RISE TO THE CLAIM OR (B) 100 USD (OR LOCAL EQUIVALENT), UNLESS A DIFFERENT LIMIT IS REQUIRED BY LAW.',
      },
      {
        title: '7. TERMINATION',
        body: 'YOU MAY STOP USING SCHNL AT ANY TIME. SOME FEATURES MAY REQUIRE YOU TO COMPLETE PENDING TRANSACTIONS OR WITHDRAW FUNDS BEFORE CLOSING.\n\nWE MAY SUSPEND, LIMIT, OR TERMINATE YOUR ACCESS IMMEDIATELY IF WE SUSPECT FRAUD, UNAUTHORIZED ACTIVITY, OR VIOLATIONS OF THESE AGREEMENTS, OR IF REQUIRED BY LAW, REGULATORS, OR PROVIDERS.\n\nSECTIONS RELATING TO FEES, LIABILITY LIMITATIONS, DISPUTES, AND GOVERNING LAW SURVIVE TERMINATION.',
      },
      {
        title: '8. GOVERNING LAW',
        body: 'THE GOVERNING LAW AND DISPUTE PROCESS MAY DEPEND ON YOUR COUNTRY OF RESIDENCE AND THE APPLICABLE PROVIDER TERMS FOR SPECIFIC FEATURES.\n\nUNLESS REQUIRED OTHERWISE BY LOCAL LAW, YOU AGREE TO FIRST CONTACT SCHNL SUPPORT TO SEEK AN INFORMAL RESOLUTION.\n\nIF A DISPUTE CANNOT BE RESOLVED INFORMALLY, IT MAY BE SUBJECT TO COURT PROCEEDINGS OR OTHER DISPUTE RESOLUTION MECHANISMS AS REQUIRED BY LAW.',
      },
      {
        title: '9. DISPUTES, CHARGEBACKS, AND REVERSALS',
        body: 'TRANSACTIONS MAY BE FINAL OR IRREVERSIBLE DEPENDING ON THE RAIL (CARD, TRANSFER, OR OTHER).\n\nIF YOU BELIEVE A TRANSACTION IS UNAUTHORIZED OR INCORRECT, CONTACT SCHNL SUPPORT PROMPTLY. WE MAY REQUIRE ADDITIONAL INFORMATION TO INVESTIGATE.\n\nCHARGEBACK RIGHTS, IF ANY, ARE GOVERNED BY YOUR CARD NETWORK RULES AND ISSUER TERMS. SCHNL DOES NOT GUARANTEE SUCCESSFUL CHARGEBACKS.',
      },
      {
        title: '10. PROHIBITED USE',
        body: 'YOU MUST NOT USE SCHNL FOR ANY ILLEGAL ACTIVITY OR FOR ANY ACTIVITY THAT VIOLATES THESE AGREEMENTS, APPLICABLE LAW, OR PROVIDER RULES.\n\nWITHOUT LIMITATION, YOU MUST NOT USE SCHNL FOR OR IN CONNECTION WITH:\n\n(A) FRAUD, SCAMS, OR DECEPTIVE PRACTICES, INCLUDING PHISHING, IDENTITY THEFT, ACCOUNT TAKEOVERS, SOCIAL ENGINEERING, FAKE INVOICES, OR MISREPRESENTATION OF GOODS OR SERVICES.\n\n(B) MONEY LAUNDERING, TERRORIST FINANCING, OR EVASION OF AML/KYC CONTROLS, INCLUDING USING STRAW ACCOUNTS, STRUCTURING TRANSACTIONS, OR USING SCHNL TO OBSCURE THE SOURCE OR DESTINATION OF FUNDS.\n\n(C) SANCTIONS EVASION OR DEALINGS WITH SANCTIONED PERSONS, COUNTRIES, OR ENTITIES, OR ANY ACTIVITY THAT WOULD CAUSE SCHNL OR ITS PROVIDERS TO VIOLATE SANCTIONS, EXPORT CONTROLS, OR SIMILAR RESTRICTIONS.\n\n(D) ILLEGAL GOODS OR SERVICES, INCLUDING THE SALE, PURCHASE, OR FACILITATION OF ILLEGAL DRUGS OR CONTROLLED SUBSTANCES, ILLEGAL PHARMACEUTICALS, COUNTERFEIT GOODS, STOLEN GOODS, OR PIRATED CONTENT.\n\n(E) ADULT OR SEXUAL CONTENT OR SERVICES WHERE PROHIBITED BY LAW OR PROVIDER RULES, INCLUDING PORNOGRAPHY, SEXUAL SERVICES, ESCORTING, OR ANY ACTIVITY INVOLVING SEXUAL EXPLOITATION OR HUMAN TRAFFICKING.\n\n(F) CHILD SEXUAL ABUSE MATERIAL (CSAM) OR ANY CONTENT OR ACTIVITY INVOLVING THE SEXUAL EXPLOITATION OF MINORS.\n\n(G) HATE, HARASSMENT, OR VIOLENCE, INCLUDING THE PROMOTION OF VIOLENCE, TERRORISM, EXTREMISM, OR HATE AGAINST PROTECTED GROUPS.\n\n(H) WEAPONS OR HAZARDOUS MATERIALS, INCLUDING FIREARMS, AMMUNITION, EXPLOSIVES, OR INSTRUCTIONS FOR ILLEGAL WEAPON MANUFACTURE, WHERE PROHIBITED BY LAW OR PROVIDER RULES.\n\n(I) GAMBLING, BETTING, LOTTERIES, OR PRIZE SCHEMES WHERE PROHIBITED OR RESTRICTED, INCLUDING UNLICENSED GAMBLING OPERATIONS.\n\n(J) UNAUTHORIZED ACCESS OR SYSTEM ABUSE, INCLUDING ATTEMPTS TO BYPASS SECURITY CONTROLS, INTERFERE WITH SERVICE OPERATION, SCRAPE DATA, REVERSE ENGINEER, OR ACCESS ACCOUNTS YOU DO NOT OWN.\n\n(K) ANY ACTIVITY THAT IS OTHERWISE ILLEGAL, UNLAWFUL, OR RESTRICTED BY SCHNL OR PROVIDERS IN THEIR COMPLIANCE PROGRAMS.\n\nWE MAY MONITOR, BLOCK, SUSPEND, LIMIT, OR TERMINATE ACCESS, AND WE MAY REPORT SUSPICIOUS ACTIVITY TO AUTHORITIES OR PROVIDERS WHEN REQUIRED OR PERMITTED BY LAW.',
      },
    ];
  }, []);

  return (
    <SafeAreaView className="flex-1 bg-white">
      <BackButton />
      <KeyboardAwareScrollView
        className="flex-1"
        showsVerticalScrollIndicator={false}
        keyboardDismissMode="interactive"
        contentContainerClassName="px-5 pt-6 pb-10">
        <View className="mb-6">
          <Text className="font-parafina text-4xl font-semibold text-neutral-900">
            Our agreements
          </Text>
          <Text className="mt-3 text-base text-neutral-500">
            Please read these agreements carefully.
          </Text>
        </View>

        <View className="rounded-2xl bg-neutral-50 px-4 py-4">
          <Text className="text-xs font-medium text-neutral-500">LAST UPDATED</Text>
          <Text className="mt-1 text-sm font-medium text-neutral-900">DECEMBER 28, 2025</Text>
        </View>

        <View className="mt-6">
          {sections.map((section) => {
            return (
              <View key={section.title} className="mb-6">
                <Text className="font-parafina text-xl font-semibold text-neutral-900">
                  {section.title}
                </Text>
                <Text
                  className="mt-3 text-sm leading-6 text-neutral-700"
                  style={{ textTransform: 'uppercase' }}>
                  {section.body}
                </Text>
              </View>
            );
          })}
        </View>
      </KeyboardAwareScrollView>
    </SafeAreaView>
  );
}
