export const BANKING_ROUTES = {
  base: "/v1/banking",
  kycLink: () => "/v1/banking/kyc-link",
  customerAddress: () => "/v1/banking/customer-address",
  limits: () => "/v1/banking/limits",
  virtualAccounts: () => "/v1/banking/virtual-accounts",
  transactions: () => "/v1/banking/transactions",
  transactionCategoryById: (id: string) =>
    `/v1/banking/transactions/${id}/category`,
  transactionNoteById: (id: string) => `/v1/banking/transactions/${id}/note`,
  transactionAttachmentsById: (id: string) =>
    `/v1/banking/transactions/${id}/attachments`,
  transactionAttachmentById: (id: string, attachmentId: string) =>
    `/v1/banking/transactions/${id}/attachments/${attachmentId}`,
  transactionReceiptById: (id: string) =>
    `/v1/banking/transactions/${id}/receipt`,
  transactionReceiptEmailById: (id: string) =>
    `/v1/banking/transactions/${id}/email-receipt`,
  recipients: () => "/v1/banking/recipients",
  recipientById: (id: string) => `/v1/banking/recipients/${id}`,
  balances: () => "/v1/banking/balances",
  fxRate: () => "/v1/banking/fx-rate",
  payRequestsByEmail: () => "/v1/banking/pay-requests/email",
  payRequestById: (id: string) => `/v1/banking/pay-requests/${id}`,
  payRequestClaim: () => "/v1/banking/pay-requests/claim",
  payRequestCancel: (id: string) => `/v1/banking/pay-requests/${id}/cancel`,
  payRequestPayoutDetails: (id: string) =>
    `/v1/banking/pay-requests/${id}/payout-details`,
  payRequestPayoutPrecheck: (id: string) =>
    `/v1/banking/pay-requests/${id}/payout-precheck`,
  outgoingPayouts: () => "/v1/banking/outgoing-payouts",
  outgoingPayoutPrecheck: () => "/v1/banking/outgoing-payouts/precheck",
  peerToPeerTransfers: () => "/v1/banking/peer-to-peer-transfers",
  peerToPeerTransfersPrecheck: () =>
    "/v1/banking/peer-to-peer-transfers/precheck",
  activate: () => "/v1/banking/activate",
  activateChallenge: () => "/v1/banking/activate/challenge",
  embeddedWallet: () => "/v1/banking/embedded-wallet",
  sessionConfig: () => "/v1/banking/session-config",
  sessionRegister: () => "/v1/banking/session/register",
  sessionTestTx: () => "/v1/banking/session/test-tx",
  sessionStatus: () => "/v1/banking/session/status",
  bankStatement: () => "/v1/banking/bank-statement",
} as const;

export const BANKING_ROUTE_PATTERNS = {
  kycLink: "/kyc-link",
  customerAddress: "/customer-address",
  limits: "/limits",
  virtualAccounts: "/virtual-accounts",
  transactions: "/transactions",
  transactionCategoryById: "/transactions/:id/category",
  transactionNoteById: "/transactions/:id/note",
  transactionAttachmentsById: "/transactions/:id/attachments",
  transactionAttachmentById: "/transactions/:id/attachments/:attachmentId",
  transactionReceiptById: "/transactions/:id/receipt",
  transactionReceiptEmailById: "/transactions/:id/email-receipt",
  recipients: "/recipients",
  recipientById: "/recipients/:id",
  balances: "/balances",
  fxRate: "/fx-rate",
  payRequestsByEmail: "/pay-requests/email",
  payRequestById: "/pay-requests/:id",
  payRequestClaim: "/pay-requests/claim",
  payRequestCancel: "/pay-requests/:id/cancel",
  payRequestPayoutDetails: "/pay-requests/:id/payout-details",
  payRequestPayoutPrecheck: "/pay-requests/:id/payout-precheck",
  outgoingPayouts: "/outgoing-payouts",
  outgoingPayoutPrecheck: "/outgoing-payouts/precheck",
  peerToPeerTransfers: "/peer-to-peer-transfers",
  peerToPeerTransfersPrecheck: "/peer-to-peer-transfers/precheck",
  activate: "/activate",
  activateChallenge: "/activate/challenge",
  embeddedWallet: "/embedded-wallet",
  sessionConfig: "/session-config",
  sessionRegister: "/session/register",
  sessionTestTx: "/session/test-tx",
  sessionStatus: "/session/status",
  bankStatement: "/bank-statement",
} as const;
